sudo: false
language: node_js
node_js:
  # NB this should be 4.4, we just have to check in occasionally to see if they
  # support it yet.
  - "4.4"
#cache:
#  directories:
#  - bower_components
#  - node_modules
branches:
    only:
        - master
        - develop
        
        
#branches:
#  only:
#    - develop
#    - staging
#    - master
#before_install:
#  - npm install -g bower
#  - npm install -g grunt-cli
install:
    - make init
    - make build config=ci
script: make test-travis
