## Build Configuration
---
plugins:
    # Plugins which come-with kbase-ui
    -
        mainwindow
    -
        message
    -
        welcome
    -
        login
    -
        userprofile
    -
        datasearch
    -
        homologyservice
    -
        narrativemanager
    -
        catalog
    # external:
    # These are shared with production
    -
        name: viswidgets
        globalName: kbase-ui-plugin-vis-widgets
        cwd: src/plugin
        version: 1.1.4
        source:
            bower: {}
    -
        name: typeview
        globalName: kbase-ui-plugin-typeview
        cwd: src/plugin
        version: 1.0.3
        source:
            bower: {}
    -
        name: dataview
        globalName: kbase-ui-plugin-dataview
        version: 1.5.4-beta
        cwd: src/plugin
        source:
            bower: {}
    -
        name: dashboard
        globalName: kbase-ui-plugin-dashboard
        version: 1.2.0
        cwd: src/plugin
        source:
            bower: {}
    # These are just developer
    -
        name: viswidgetdemo
        globalName: kbase-ui-plugin-demo-vis-widget
        cwd: src/plugin
        version: 1.0.0
        source:
            bower: {}
    -
        name: databrowser
        globalName: kbase-ui-plugin-databrowser
        version: 1.0.0
        cwd: src/plugin
        source:
            bower: {}
    -
        name: typebrowser
        globalName: kbase-ui-plugin-typebrowser
        version: 1.0.0
        cwd: src/plugin
        source:
            bower: {}
    -
        name: datawidgets
        globalName: kbase-ui-plugin-datawidgets
        version: 0.1.6
        cwd: src/plugin
        source:
            bower: {}
    -
        name: data-landing-pages
        globalName: kbase-ui-plugin-data-landing-pages
        version: 0.3.0
        cwd: src/plugin
        source:
            bower: {}
    -
        name: dataapidemo
        globalName: kbase-ui-plugin-data-api-demo
        version: 0.1.5
        cwd: src/plugin
        source:
            bower: {}
    -
        name: shockbrowser
        globalName: kbase-ui-plugin-shockbrowser
        version: 0.1.2
        cwd: src/plugin
        source:
            bower: {}
    -
        name: jobbrowser
        globalName: kbase-ui-plugin-jobbrowser
        version: 0.1.2
        cwd: src/plugin
        source:
            bower: {}
    -
        name: methodview
        globalName: kbase-ui-plugin-methodview
        version: 1.0.1
        cwd: src/plugin
        source:
            bower: {}
    -
        name: ontology-widgets
        globalName: kbase-ui-plugin-ontology-widgets
        version: 0.1.0
        cwd: src/plugin
        source:
            bower: {}

# Copy these directories into the modules
# There are two forms, as for plugins.
# a bower: section will specify a bower dependency
# a copy: section will specify a directory to copy literally into modules
# a link: section will specify a directory to link into modules

modules:
    -
        globalName: kbase-ui-widget
        version: 1.0.8
        source:
            bower: {}
    -
        globalName: kbase-common-js
        version: 1.6.0
        source:
            bower: {}
    -
        globalName: kbase-service-clients-js
        version: 1.6.0
        source:
            bower: {}
    -
        globalName: kbase-data-api-client-js
        version: 1.0.4
        source:
            bower: {}
